Repository LeaYeh/minishell, pull requests merged in 2023-12, with the labels that each got.

#6 feat: Add ft_lstinsert_after to libft
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
Labels: enhancement

#5 Fix potential segfaults and allow empty key and values in env
  source/builtins/env.c
  source/init_shell.c
Labels: bug

#8 [FEAT]: Add ft_split_at_index to libft
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/strings/ft_split_at_index.c
Labels: enhancement

#10 [FIX]: Fix ft_lstinsert_after and ft_dprintf in libft
  libraries/libft/src/ft_printf/print_ptr.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
Labels: bug

#13 [FEAT] Add ft_lstpop_content to libft
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/singly_linked/ft_lstpop_content.c
Labels: enhancement

#15 [FEAT] Feature-complete lexer
  Makefile
  include/defines.h
  include/lexer.h
  include/minishell.h
  include/tests.h
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/get_data.c
  source/frontend/lexer/get_type.c
  source/frontend/lexer/lexer.c
  source/frontend/lexer/lexer_utils.c
  source/main.c
  tests/test_lexer.c
Labels: enhancement, todo

#17 [DOC] Improve libft documentation for custom functions
  libraries/libft/src/libft/chars/ft_isspace.c
  libraries/libft/src/libft/lists/doubly_linked/ft_lstadd_back_d.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstpop.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstpop_content.c
  libraries/libft/src/libft/memory/ft_free_and_null.c
  libraries/libft/src/libft/memory/ft_memcpy.c
  libraries/libft/src/libft/memory/ft_memmove.c
  libraries/libft/src/libft/put/ft_putnbr_base_fd.c
  libraries/libft/src/libft/put/ft_putnchar_fd.c
  libraries/libft/src/libft/put/ft_putnstr_fd.c
  libraries/libft/src/libft/strings/ft_split_at_index.c
  libraries/libft/src/libft/strings/ft_strisdigits.c
  libraries/libft/src/libft/strings/ft_strlcat.c
  libraries/libft/src/libft/strings/ft_strlcpy.c
  libraries/libft/src/libft/strings/ft_strlen.c
  libraries/libft/src/libft/strings/ft_strmatches_any.c
  libraries/libft/src/libft/strings/ft_strnstr.c
  libraries/libft/src/libft/strings/ft_strtok.c
Labels: documentation

#20 [FIX] action mask in match rule is necessary
  source/frontend/parser/parsing_table.c
Labels: bug

#27 [CI] Set up GitHub Actions by creating build.yml
  .github/workflows/build.yml
Labels: development

#24 [FIX] Set T_ASSIGNMENT_WORD token types correctly in lexer
  include/lexer.h
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/finetune_token_list.c
  source/frontend/lexer/get_token_data_list.c
  source/frontend/lexer/lexer.c
  source/frontend/lexer/lexer_utils.c
  source/frontend/lexer/set_token_type.c
Labels: enhancement

#28 [BUILD] Improve Makefile
  Makefile
Labels: enhancement

#39 [FIX] Skip the empty input
  source/main.c
Labels: enhancement

#45 [FIX] Fix memory leak by freeing `ast` before reading new input
  source/main.c
Labels: leak

#40 [FIX] Resolve questions about function pointer cast to `(void *)` + some standardization
  include/clean.h
  include/utils.h
  libraries/libft/src/libft/strings/ft_split.c
  libraries/libft/src/libft/strings/ft_split_at_index.c
  source/builtins/env.c
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/finetune_token_list.c
  source/frontend/lexer/lexer_utils.c
  source/frontend/lexer/set_token_type.c
  source/frontend/parser/parse.c
  source/frontend/parser/parser_operation.c
  source/init_shell.c
  source/main.c
  source/shell_clean.c
  source/utils/ast_utils.c
  source/utils/stack_utils.c
  source/utils/token_utils.c
  tests/test_lexer.c
Labels: enhancement

#48 [FIX] Fix potential segfault in ft_lstinsert_after in libft
  libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
  source/frontend/lexer/lexer_utils.c
Labels: bug

#56 [CI] Add diff report to GH Actions
  .github/workflows/test.yml
  Makefile
Labels: enhancement, development

#57 [CI] Let diff not fail a GH Actions test
  .github/workflows/test.yml
Labels: bug, development
