Repository LeaYeh/minishell, pull requests merged in 2024-04, with the labels that each got.

#283 [FIX] Fix wrong null-expansion after word-splitting and quote combination
  Makefile
  build/source_files.mk
  include/defines.h
  include/expander.h
  include/heredoc.h
  include/utils.h
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/null_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/special_param_expansion.c
  source/frontend/expander/variable_expansion.c
  source/frontend/expander/word_splitting.c
  source/frontend/expander/word_splitting_utils.c
  source/utils/string_utils.c
  todo
Labels: bug

#297 [STYLE] Various tiny style changes and change `shell->exit_code` to `unsigned char`
  build/parsing_table.mk
  include/defines.h
  source/backend/builtins/exit/exit.c
  source/signal/signal_handler.c
Labels: chore

#294 [CI] Trigger test workflow when add new tag version
  .github/workflows/test.yaml
Labels: development

#292 [FEAT] Implement wildcard expansion for the current directory
  build/source_files.mk
  include/debug.h
  include/defines.h
  include/expander.h
  include/utils.h
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_before.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstsort_merge.c
  libraries/libft/src/libft/strings/ft_alphabetic.c
  libraries/libft/src/libft/strings/ft_strrnstr.c
  source/backend/executor/executor_utils.c
  source/backend/redirection/io_file.c
  source/debug/print_expanded_cmd_table_content.c
  source/debug/print_expander_task_list.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/expander/expander_task_utils.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/parameter_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/special_param_expansion.c
  source/frontend/expander/wildcard_expansion.c
  source/frontend/expander/wildcard_expansion_utils.c
  source/frontend/expander/wildcard_file_list.c
  source/frontend/expander/wildcard_task_list.c
  source/frontend/expander/word_splitting.c
  source/utils/final_cmd_table_setup.c
  source/utils/varname_utils.c
  todo
Labels: feature

#298 [FIX] Fix filename expansion in non-interactive mode
  .github/workflows/test.yaml
  Makefile
  include/defines.h
  source/backend/builtins/exit/exit.c
  source/backend/redirection/io_file.c
  source/shell_struct/init.c
Labels: bug, enhancement

#299 [STYLE] Rename expander variable names
  include/defines.h
  include/expander.h
  source/backend/executor/executor_utils.c
  source/backend/redirection/heredoc_utils.c
  source/backend/redirection/io_file.c
  source/debug/print_ast_bfs.c
  source/debug/print_expanded_cmd_table_content.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/null_expansion.c
  source/frontend/expander/parameter_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/wildcard_expansion.c
  source/frontend/expander/wildcard_file_list.c
  source/frontend/expander/wildcard_task_list.c
  source/frontend/expander/word_splitting.c
  source/frontend/expander/word_splitting_utils.c
  source/utils/final_cmd_table_setup.c
  todo
Labels: leak, chore

#301 [FIX] Make `read_input()` more general and also us it in heredoc
  build/source_files.mk
  source/backend/redirection/heredoc.c
  source/main.c
  source/shell/clean.c
  source/shell/default_env_list.c
  source/shell/env_list.c
  source/shell/init.c
  source/shell/read_input.c
Labels: enhancement, help needed

#302 [DOC] Update badge colors in README
  README.md
Labels: documentation

#303 [CHORE] Put `read_input()` into utils
  build/source_files.mk
  include/utils.h
  source/backend/redirection/heredoc.c
  source/main.c
  source/utils/user_input_utils.c
Labels: chore

#304 [STYLE] Change all occurances of `2` to `STDERR_FILENO`
  source/backend/builtins/cd/cd_utils.c
  source/backend/builtins/exit/exit.c
  source/backend/builtins/pwd.c
  source/backend/redirection/io_file.c
  source/utils/file_utils.c
Labels: chore

#310 [BUILD] Print version of compiler when compiling
  Makefile
Labels: development

#309 [FIX] Fix `PT_ROWS` size
  include/defines.h
  source/frontend/parser/parsing_table_operation.c
Labels: bug, chore

#311 [BUILD] Change Makefile to always compile in parallel
  Makefile
Labels: bug

#312 [CHORE] Use enumed types whenever possible
  build/parsing_table.mk
  include/builtins.h
  include/defines.h
  include/heredoc.h
  include/parser.h
  include/utils.h
  meta/gen_action_table.py
  meta/parsing_table.md
  source/backend/builtins/exit/exit.c
  source/backend/builtins/exit/exit_utils.c
  source/backend/executor/control_operator.c
  source/backend/executor/executor.c
  source/backend/executor/pipeline_process.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/debug/print_ast_bfs.c
  source/debug/print_list.c
  source/debug/print_stack.c
  source/frontend/lexer/token_list_post_processing.c
  source/frontend/lexer/token_type.c
  source/frontend/parser/cmd_table_list.c
  source/frontend/parser/cmd_table_symbol.c
  source/frontend/parser/cmd_table_symbol_utils.c
  source/frontend/parser/parser.c
  source/frontend/parser/parser_action.c
  source/frontend/parser/parsing_table_operation.c
  source/utils/ast_utils.c
  source/utils/cmd_table_list_utils.c
  source/utils/cmd_table_operation_utils.c
  source/utils/cmd_table_traversal_utils.c
  source/utils/cmd_table_type_utils.c
  source/utils/token_status_utils.c
  source/utils/token_type_utils.c
  source/utils/token_utils.c
Labels: chore

#314 [STYLE] Rename `token_node` to `token` when not a `t_list`
  include/lexer.h
  include/parser.h
  include/utils.h
  source/frontend/lexer/lexer_utils.c
  source/frontend/lexer/token_list.c
  source/frontend/lexer/token_type.c
  source/frontend/parser/parser.c
  source/frontend/parser/parser_action.c
  source/frontend/parser/parser_data.c
  source/shell/clean.c
  source/utils/token_utils.c
Labels: chore

#315 [STYLE] Make function signatures consistent
  include/cd.h
  include/executor.h
  include/expander.h
  include/heredoc.h
  include/parser.h
  include/utils.h
  source/backend/builtins/cd/component_list.c
  source/backend/builtins/cd/component_list_utils.c
  source/backend/builtins/export/export_output.c
  source/backend/executor/executor_utils.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/backend/redirection/io_file.c
  source/debug/print_ast_bfs.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/expander/expander_task_utils.c
  source/frontend/expander/wildcard_expansion.c
  source/frontend/expander/wildcard_task_list.c
  source/frontend/expander/word_splitting.c
  source/frontend/expander/word_splitting_utils.c
  source/frontend/lexer/token_list.c
  source/frontend/parser/cmd_table_list.c
  source/frontend/parser/parser_action.c
  source/frontend/parser/parsing_table_operation.c
  source/utils/cmd_table_list_utils.c
  source/utils/env_list_operation_utils.c
  source/utils/expansion_utils.c
  source/utils/final_cmd_table_setup.c
  source/utils/user_input_utils.c
Labels: chore

#316 [STYLE] Change color/style macro names and add them also to Makefile
  Makefile
  include/defines.h
  source/debug/print_expanded_cmd_table.c
  source/debug/print_expander_task_list.c
Labels: chore

#317 [CI] Print the outputs of the failed testcases
  .github/actions/setup/action.yaml
  .github/actions/summary_test_result/action.yaml
  .github/scripts/print_all_failed_test_cases.sh
  .github/scripts/print_changed_test_cases.sh
  .github/scripts/print_leak_test_cases.sh
  .github/scripts/print_test_case.sh
  .github/workflows/delivery.yaml
  .github/workflows/test.yaml
Labels: development

#319 [FIX] Fix issues detected by cppcheck
  libraries/libft/src/ft_printf/ft_snprintf/sprint_nbr.c
  libraries/libft/src/ft_printf/print_nbr.c
  libraries/libft/src/libft/put/ft_putnbr_base_fd.c
  libraries/libft/src/libft/put/ft_putnbr_fd.c
  libraries/libft/src/libft/put/ft_snputnbr_base.c
  source/signal/signal_handler.c
  source/utils/symbol_utils.c
Labels: bug

#323 [LIB] Use bitwise operators in basic alphabet functions to improve performance
  libraries/libft/src/libft/chars/ft_isalpha.c
  libraries/libft/src/libft/chars/ft_tolower.c
  libraries/libft/src/libft/chars/ft_toupper.c
Labels: enhancement

#321 [DOC] Make wave emoji italic to make the C in 🌊rash more obvious
  README.md
Labels: documentation

#327 [FIX] Replace forbidden `getpid()` function with custom version
  build/source_files.mk
  include/utils.h
  source/shell/init.c
  source/signal/exception_broadcaster.c
  source/utils/file_utils.c
  source/utils/pid_utils.c
Labels: chore

#328 [BUILD] Makefile improvements
  Makefile
  libraries/libft/Makefile
Labels: enhancement

#326 [REVERT] Revert PR #323
  libraries/libft/src/libft/chars/ft_isalpha.c
  libraries/libft/src/libft/chars/ft_tolower.c
  libraries/libft/src/libft/chars/ft_toupper.c
Labels: bug
