Repository LeaYeh/minishell, pull requests merged in 2024-02, with the labels that each got.

#140 [FIX] Replace parsing table global variable with macro that gets defined in the Makefile
  Makefile
  build/parsing_table.mk
  include/defines.h
  source/frontend/parser/parsing_table.c
Labels: todo

#142 [FIX] Hotfix pipe redirection bug
  Makefile
  include/utils.h
  source/backend/executor/executor.c
  source/backend/executor/handle_builtin.c
  source/shell_clean.c
  source/utils/final_cmd_table_utils.c
Labels: bug

#146 [FIX] Protect if PARSING_TABLE macro is not defined
  include/defines.h
  source/main.c
Labels: chore

#148 [CI] Add emojis to comparison printout in GH Actions to differentiate more easily between the branches
  .github/scripts/print_changed_test_cases.sh
Labels: enhancement, development

#151 [FEAT] Add heredoc mask to expander to expand even inside single quotes
  include/defines.h
  include/expander.h
  include/heredoc.h
  include/utils.h
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/debug/print_expanded_cmd_table.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/parameter_expansion.c
  source/utils/expansion_utils.c
  source/utils/final_cmd_table_utils.c
Labels: enhancement

#152 [BUILD] Makefile enhancements + add clang-12 to GH Actions environment
  .github/workflows/test.yml
  Makefile
  libraries/libft/Makefile
Labels: development

#154 [CI] Split up GH Actions tests into multiple jobs to run in parallel
  .github/scripts/print_all_failed_test_cases.sh
  .github/scripts/print_changed_test_cases.sh
  .github/workflows/test.yml
Labels: development

#150 [FEAT] Implement heredoc expansion
  include/defines.h
  include/executor.h
  include/expander.h
  include/heredoc.h
  include/utils.h
  source/backend/executor/executor.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/builtins/echo.c
  source/debug/print_expanded_cmd_table.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/parameter_expansion.c
  source/utils/expansion_utils.c
  source/utils/file_utils.c
  source/utils/final_cmd_table_utils.c
  source/utils/string_utils.c
Labels: feature

#163 [FIX] Handle non-existing PATH env variable for getting the exec path
  include/cd.h
  source/backend/executor/executor_utils.c
  source/builtins/cd/environment_utils.c
  source/builtins/cd/get_target_dir.c
Labels: bug

#166 [FEAT] Implement export without arguments -> print out the exported environment
  include/builtins.h
  include/defines.h
  include/export.h
  source/backend/executor/handle_builtin.c
  source/builtins/export/export.c
  source/builtins/export/print_exported_env.c
Labels: question, feature

#167 [FEAT] Implement full export with arguments
  .gitignore
  include/export.h
  include/init.h
  include/utils.h
  source/builtins/export/export.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expand_variable.c
  source/frontend/expander/expander_utils.c
  source/frontend/lexer/set_token_type.c
  source/init/setup_env_list.c
  source/utils/env_list_utils.c
  source/utils/env_utils.c
  source/utils/string_utils.c
  todo
Labels: feature

#170 [FEAT] Implement unset
  Makefile
  include/builtins.h
  source/backend/executor/handle_builtin.c
  source/builtins/unset.c
Labels: feature

#172 [FEAT] Add missing quote and brace detection to lexer
  include/defines.h
  include/lexer.h
  include/utils.h
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/parameter_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/remove_quotes.c
  source/frontend/lexer/create_token_data_list.c
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/lexer_utils.c
  source/utils/string_utils.c
Labels: feature

#180 [FIX] Fix multi `-n` detection for echo
  source/builtins/echo.c
Labels: bug

#178 [FIX] Fix wrong token recognition of single `&`
  include/defines.h
  include/lexer.h
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/lexer_utils.c
Labels: bug

#184 [FIX] Fix `exit ""`
  source/builtins/exit_utils.c
Labels: bug

#177 [FIX] Fix quote removal coming from variable expansions
  include/defines.h
  include/expander.h
  include/utils.h
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/strings/ft_strndup.c
  libraries/libft/src/libft/strings/ft_strrplc_part.c
  libraries/libft/src/libft/strings/ft_strrplc_sequence.c
  minishell.supp
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_stack.c
  source/frontend/expander/expander_task_stack_utils.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/expansion_handler.c
  source/frontend/expander/parameter_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/special_param_expansion.c
  source/frontend/expander/variable_expansion.c
  source/utils/string_utils.c
Labels: bug

#187 [FIX] Fix executable search
  .vscode/launch.json
  include/defines.h
  include/executor.h
  include/utils.h
  source/backend/executor/exec_error.c
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_external.c
  source/utils/exec_path_setup_utils.c
  source/utils/final_cmd_table_setup.c
  source/utils/final_cmd_table_utils.c
Labels: bug
