Repository LeaYeh/minishell, pull requests merged in 2024-03, with the labels that each got.

#195 [FIX] Fix leaks and protections in `ft_read_input()`
  source/main.c
Labels: bug

#197 [FIX] Free the static buffer in `get_next_line()`
  libraries/libft/src/get_next_line/get_next_line.c
  source/shell_clean.c
Labels: leak

#194 [FIX] Fix memory leaks when SIGPIPE occured in minishell child process
  .github/actions/setup/action.yaml
  Makefile
  source/backend/executor/handle_simple_cmd.c
Labels: leak

#175 [FIX] No newline was printed with the exit string when Ctrl+D
  Makefile
  include/defines.h
  include/signals.h
  source/backend/executor/handle_pipeline.c
  source/builtins/exit.c
  source/init/init_shell.c
  source/main.c
  source/shell_clean.c
  source/signal/signal.c
  source/utils/process_utils.c
Labels: bug

#204 [FEAT] Implement expander word splitting
  include/defines.h
  include/expander.h
  libraries/libft/src/libft/strings/ft_split_at_index.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/expander/expansion_handler.c
  source/frontend/expander/null_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/special_param_expansion.c
  source/frontend/expander/variable_expansion.c
  source/frontend/expander/word_splitting.c
  source/frontend/lexer/lexer_utils.c
Labels: feature

#208 [FIX] Fix order of redirections for subshells
  include/executor.h
  include/utils.h
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/bind.c
  source/backend/redirection/io_redirect.c
  source/frontend/parser/cmd_table_symbol.c
  source/utils/cmd_table_status_utils.c
Labels: bug

#224 [FIX] Don't add empty lines to the history
  source/main.c
Labels: enhancement

#218 [FIX] Fix unresponsiveness after terminal window resizing
  source/main.c
Labels: bug

#219 [STYLE] Change default cmd_table type and remove dead return statements
  .github/workflows/test.yaml
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_simple_cmd.c
  source/frontend/parser/cmd_table_symbol.c
  source/utils/cmd_table_operation_utils.c
  source/utils/cmd_table_status_utils.c
Labels: development, chore

#205 [FIX] Stop full cmd list if received `Ctrl+C`
  include/defines.h
  include/signals.h
  source/backend/executor/executor.c
  source/backend/executor/handle_control_op.c
  source/backend/executor/handle_pipeline.c
  source/init/init_shell.c
  source/shell_clean.c
  source/signal/signal.c
Labels: bug

#212 [FIX] Expand target filename when handle io redirection
  include/defines.h
  include/executor.h
  include/expander.h
  include/heredoc.h
  include/utils.h
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/bind.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/backend/redirection/io_redirect.c
  source/debug/print_cmd_table.c
  source/debug/print_expanded_cmd_table.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expansion_handler.c
  source/frontend/parser/cmd_table_symbol.c
  source/utils/expansion_utils.c
  source/utils/final_cmd_table_setup_utils.c
  source/utils/io_redirect_utils.c
  source/utils/string_utils.c
Labels: bug

#216 [FIX] Fix word splitting not removing beginning space
  include/expander.h
  source/backend/redirection/heredoc_utils.c
  source/frontend/expander/expansion_handler.c
  source/frontend/expander/null_expansion.c
  source/frontend/expander/word_splitting.c
Labels: bug

#217 [FIX] Fix Ctrl+D in heredoc printing one too much line
  include/defines.h
Labels: bug

#220 [FIX] Change back to waiting for child processes from the back
  include/utils.h
  source/backend/executor/handle_pipeline.c
  source/utils/process_utils.c
Labels: enhancement

#225 [FIX] Fix bad substitution impact on the rest of the commands and exit code
  include/executor.h
  include/utils.h
  source/backend/executor/executor.c
  source/backend/executor/handle_pipeline.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/heredoc_utils.c
  source/shell_clean.c
  source/utils/env_list_status_utils.c
  source/utils/final_cmd_table_setup.c
  source/utils/final_cmd_table_setup_utils.c
  source/utils/final_cmd_table_utils.c
Labels: bug

#226 [FIX] Fix and standardize exception exit codes
  include/cd.h
  include/defines.h
  include/executor.h
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/bind.c
  source/builtins/cd/cd.c
  source/builtins/cd/cd_errors.c
  source/builtins/cd/cmpnt_list_utils.c
  source/builtins/cd/process_path.c
  source/builtins/export/export.c
  source/builtins/export/print_exported_env.c
Labels: enhancement

#227 [FIX] Fix norm issues of builtins modules
  source/builtins/cd/cd.c
  source/builtins/echo.c
  source/builtins/exit.c
  source/builtins/exit_utils.c
  source/builtins/export/export.c
  source/builtins/export/print_exported_env.c
  source/builtins/pwd.c
  source/builtins/unset.c
Labels: chore

#229 [FIX] Fix norm issues of expander module
  source/frontend/expander/expander.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/expander/expansion_handler.c
  source/frontend/expander/null_expansion.c
  source/frontend/expander/word_splitting.c
Labels: chore

#231 [FIX] Fix norm issues of init module
  source/init/init_shell.c
  source/init/setup_default_env_list.c
  source/init/setup_env_list.c
Labels: chore

#230 [FIX] Fix norm issues of parser module
  include/utils.h
  source/frontend/parser/cmd_table_symbol.c
  source/frontend/parser/cmd_table_symbol_utils.c
  source/frontend/parser/parser.c
  source/frontend/parser/parser_operation.c
Labels: chore

#232 [FIX] Fix norm issues of utils folder
  include/utils.h
  source/utils/expansion_utils.c
  source/utils/process_utils.c
Labels: chore

#237 [STYLE] Fix the norm issue of executor module
  include/defines.h
  include/executor.h
  source/backend/executor/executor.c
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_assignment.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_control_op.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_pipeline.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
Labels: chore

#238 [STYLE] Fix norm issue which missed checking
  include/executor.h
  source/shell_clean.c
  tests/test_lexer.c
Labels: chore

#239 [STYLE] Make Lexer more clear
  include/lexer.h
  source/frontend/lexer/lexer_utils.c
Labels: chore

#240 [STYLE] Fix norminette in ft_snprintf
  libraries/libft/inc/ft_printf.h
  libraries/libft/src/ft_printf/ft_snprintf/get_max_size.c
  libraries/libft/src/ft_printf/ft_snprintf/parseandsprint.c
  libraries/libft/src/ft_printf/ft_snprintf/sprint_char.c
  libraries/libft/src/ft_printf/ft_snprintf/sprint_nbr.c
  libraries/libft/src/ft_printf/ft_snprintf/sprint_parsed.c
  libraries/libft/src/ft_printf/ft_snprintf/sprint_ptr.c
  libraries/libft/src/ft_printf/ft_snprintf/sprint_str.c
Labels: chore

#242 [STYLE] Fix forgotten ft_snprintf norm issue
  libraries/libft/src/ft_printf/ft_snprintf/set_sformat.c
Labels: chore

#244 [BUILD] Explicitely list all source files in a .mk file
  Makefile
  build/source_files.mk
Labels: chore

#210 [CD] Add CD auto process
  .github/workflows/delivery.yaml
Labels: development

#252 [CD] Use GITHUB_ENV instead of GITHUB_OUTPUT
  .github/workflows/delivery.yaml
Labels: development

#254 [STYLE] Cleanup defines
  include/builtins.h
  include/clean.h
  include/debug.h
  include/defines.h
  include/executor.h
  include/export.h
  include/heredoc.h
  include/minishell.h
  include/parser.h
  include/signals.h
  include/tests.h
  include/utils.h
  source/backend/executor/executor.c
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/backend/redirection/io_redirect.c
  source/backend/redirection/pipe_redirect.c
  source/backend/redirection/pipe_redirect_utils.c
  source/builtins/cd/cd.c
  source/builtins/cd/env_pwd_update.c
  source/builtins/env.c
  source/builtins/exit.c
  source/builtins/exit_utils.c
  source/builtins/export/export.c
  source/builtins/export/print_exported_env.c
  source/debug/print_cmd_table.c
  source/debug/print_list.c
  source/debug/print_stack.c
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/finetune_token_list.c
  source/frontend/lexer/lexer_utils.c
  source/frontend/parser/parser.c
  source/init/setup_default_env_list.c
  source/init/setup_env_list.c
  source/main.c
  source/shell_clean.c
  source/signal/signal_handler.c
  source/utils/cmd_table_operation_utils.c
  source/utils/cmd_table_traversal_utils.c
  source/utils/cmd_table_type_utils.c
  source/utils/env_list_op_utils.c
  source/utils/env_list_status_utils.c
  source/utils/exec_path_setup_utils.c
  source/utils/final_cmd_table_utils.c
  source/utils/io_redirect_status_utils.c
  source/utils/io_redirect_utils.c
  source/utils/process_utils.c
  source/utils/stack_status_utils.c
  source/utils/stack_utils.c
  source/utils/string_utils.c
  source/utils/token_utils.c
  source/utils/type_utils.c
Labels: chore

#255 [CHORE] Remove unwanted comments and files
  build/source_files.mk
  include/executor.h
  source/backend/executor/executor.c
  source/backend/executor/handle_assignment.c
  source/backend/redirection/heredoc.c
  source/builtins/export/print_exported_env.c
  source/debug/print_final_cmd_table.c
  source/frontend/parser/build_tree.pseudo
  source/frontend/parser/build_tree_recursive.pseudo
  source/frontend/parser/parser.c
  source/frontend/parser/parser_operation.c
  source/frontend/parser/rules
  source/main.c
  source/utils/array_utils.c
Labels: chore

#258 [STYLE] Remove `ft_` from all shell functions
  include/builtins.h
  include/clean.h
  include/executor.h
  include/expander.h
  include/heredoc.h
  include/lexer.h
  include/parser.h
  source/backend/executor/executor.c
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_pipeline.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/heredoc_utils.c
  source/backend/redirection/io_redirect.c
  source/builtins/echo.c
  source/builtins/env.c
  source/builtins/exit.c
  source/builtins/pwd.c
  source/debug/print_expanded_cmd_table.c
  source/frontend/expander/expander.c
  source/frontend/lexer/lexer.c
  source/frontend/parser/parser.c
  source/main.c
  source/shell_clean.c
  source/signal/signal_handler.c
  source/utils/expansion_utils.c
Labels: chore

#256 [FIX] Fix exit builtin with whitespace in arguments
  source/builtins/exit_utils.c
Labels: bug

#234 [FIX] Fix IO files being created in child process when no scmd
  source/backend/executor/executor.c
  source/backend/executor/handle_builtin.c
Labels: bug

#253 [CD] Rename job name to "update_evaluation_branch"
  .github/workflows/delivery.yaml
Labels: development

#259 [CD] Fix eval tag creation
  .github/workflows/delivery.yaml
Labels: development

#261 [CD] Fix eval tag creation
  .github/workflows/delivery.yaml
Labels: development

#262 [FIX] Fix exit codes from exit builtin
  source/builtins/exit.c
  source/builtins/exit_utils.c
Labels: bug

#270 [FIX] Print exit msg to stderr
  source/backend/builtins/exit/exit.c
  source/backend/builtins/exit/exit_utils.c
  source/main.c
Labels: bug

#272 [FIX] Cleanup heredoc files
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/doubly_linked/ft_lstiter_d.c
  source/shell_struct/clean.c
Labels: bug

#273 [REFACTOR] Merge `SIGINT` handling of heredoc with standard
  include/defines.h
  source/backend/executor/executor.c
  source/shell_struct/init.c
  source/signal/signal_handler.c
Labels: enhancement

#271 [CI] Add norminette test to GH Actions
  .github/actions/cleanup/action.yaml
  .github/actions/norminette/action.yaml
  .github/workflows/delivery.yaml
Labels: development

#275 [BUILD] Add `ffclean` goal to Makefile
  Makefile
Labels: enhancement

#277 [FIX] Fix funcheck without `-a` option
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/lexer/lexer_utils.c
  source/frontend/lexer/token_list.c
  source/frontend/parser/parser_data.c
  source/utils/cmd_table_operation_utils.c
  source/utils/io_redirect_utils.c
Labels: leak

#278 [FIX] Fix heredoc for subshell redirect
  source/backend/redirection/heredoc.c
Labels: leak

#276 [CI] Install funcheck in setup
  .github/actions/setup/action.yaml
Labels: development

#279 [CHORE] Avoid misleading `ft_free_and_null()`s
  source/shell_struct/clean.c
  source/utils/cmd_table_operation_utils.c
  source/utils/io_redirect_utils.c
  source/utils/token_utils.c
Labels: chore

#280 [CI] Add manually triggered norminette workflow
  .github/actions/cleanup/action.yaml
  .github/actions/norminette/action.yaml
  .github/actions/setup/action.yaml
  .github/actions/summary_test_result/action.yaml
  .github/workflows/delivery.yaml
  .github/workflows/norminette.yaml
  .github/workflows/test.yaml
Labels: development

#284 [CI/CD] Fix manually triggered norminette workflow
  .github/actions/cleanup/action.yaml
  .github/actions/cleanup_full/action.yaml
  .github/actions/cleanup_partial/action.yaml
  .github/actions/norminette/action.yaml
  .github/workflows/delivery.yaml
  .github/workflows/norminette.yaml
Labels: development

#282 [CHORE] Change `size_t` to `int`
  include/cd.h
  include/defines.h
  include/expander.h
  include/lexer.h
  include/utils.h
  source/backend/builtins/cd/component_list.c
  source/backend/builtins/cd/component_list_utils.c
  source/backend/builtins/cd/path.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/expander_task_list.c
  source/frontend/expander/expander_task_list_utils.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/word_splitting.c
  source/frontend/lexer/lexer_utils.c
  source/frontend/lexer/token_data_list.c
  source/frontend/lexer/token_list.c
  source/frontend/lexer/token_type.c
  source/utils/symbol_utils.c
Labels: chore

#288 [CHORE] Add .gitattributes file for git LFS
  .gitattributes
Labels: documentation, chore

#289 [DOC] Add notes from tablet
  doc/notes/Executor_240205_142731.pdf
  doc/notes/Notes_231206_223317.pdf
  doc/notes/Notes_231207_145758.pdf
  doc/notes/Notes_231207_191820.pdf
  doc/notes/Notes_231207_234833.pdf
  doc/notes/Notes_231224_090449.pdf
  doc/notes/Notes_240314_141022.pdf
  doc/notes/Notes_240314_142335.pdf
  doc/notes/Pipes_240123_122003.pdf
Labels: documentation

#290 [DOC] Add another process flow note
  doc/notes/Notes_240326_161820.pdf
Labels: documentation

#291 [STYLE] Fix norm issues of debug folder
  build/source_files.mk
  include/debug.h
  source/debug/print_ast_bfs.c
  source/debug/print_expanded_cmd_table.c
  source/debug/print_expanded_cmd_table_content.c
Labels: chore

#293 [CI] Add possibility to manually trigger the test workflow for any branch
  .github/workflows/test.yaml
Labels: development
