Repository LeaYeh/minishell, pull requests merged in 2024-01, with the labels that each got.

#58 [CI] Improve the order of the GH Actions result-comparison steps
  .github/workflows/test.yml
Labels: enhancement, development

#59 [CI] Ignore the error on diff
  .github/workflows/test.yml
Labels: development

#74 [REFACTOR] Change parser interface to diff between parsing and general…
  include/clean.h
  include/defines.h
  include/lexer.h
  include/parser.h
  source/builtins/env.c
  source/frontend/lexer/create_token_data_list.c
  source/frontend/lexer/create_token_list.c
  source/frontend/lexer/lexer.c
  source/frontend/parser/parser.c
  source/frontend/parser/parser_operation.c
  source/frontend/parser/parser_utils.c
  source/frontend/parser/parsing_table.c
  source/init_shell.c
  source/main.c
  source/shell_clean.c
Labels: enhancement

#87 [CI] Remove useless files to get more space in GH Actions
  .github/workflows/test.yml
Labels: development

#79 [FIX] Mount all files and folders to avoid confilict
  docker-compose.yml
Labels: development

#82 [FEAT] Implement builtin function of echo
  include/builtins.h
  include/utils.h
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_simple_cmd.c
  source/builtins/echo.c
  source/utils/file_utils.c
  source/utils/final_cmd_table_utils.c
Labels: feature

#83 [FEAT] Implement builtin function of pwd
  include/builtins.h
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_builtin.c
  source/builtins/pwd.c
Labels: todo, feature

#94 [FEAT] Apply expansion during executing command
  Makefile
  include/defines.h
  include/executor.h
  include/expander.h
  include/utils.h
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/doubly_linked/ft_lstnew_back_d.c
  libraries/libft/src/libft/lists/doubly_linked/ft_lstnew_d.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstnew.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstsize_non_null.c
  source/backend/executor/exec_error.c
  source/backend/executor/executor.c
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_assignment.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/redirection/heredoc.c
  source/builtins/echo.c
  source/debug/print_cmd_table.c
  source/debug/print_expanded_cmd_table.c
  source/debug/print_final_cmd_table.c
  source/frontend/expander/bad_substitution.c
  source/frontend/expander/create_expanded_list.c
  source/frontend/expander/expander.c
  source/frontend/expander/expander_utils.c
  source/frontend/expander/parameter_expansion.c
  source/frontend/parser/cmd_table_word.c
  source/frontend/parser/parser_operation.c
  source/frontend/parser/parsing_table.c
  source/init_shell.c
  source/main.c
  source/utils/array_utils.c
  source/utils/cmd_table_operation_utils.c
  source/utils/cmd_table_type_utils.c
  source/utils/expansion_utils.c
  source/utils/final_cmd_table_utils.c
Labels: feature

#102 [SUGGESTION] Fix overflow + slight improvements to the exit builtin
  source/builtins/exit.c
  source/builtins/exit_utils.c
Labels: enhancement

#99 [FEAT] Implement builtin of exit
  include/builtins.h
  include/defines.h
  source/backend/executor/executor.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_pipeline.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
  source/builtins/exit.c
  source/builtins/exit_utils.c
  source/debug/print_expanded_cmd_table.c
  source/frontend/expander/expander.c
  source/frontend/lexer/lexer.c
  source/frontend/parser/parser.c
  source/main.c
  source/utils/expansion_utils.c
  source/utils/final_cmd_table_utils.c
  source/utils/process_utils.c
Labels: feature

#104 [CI] Revert the commits that let the GH Actions not prevent a merge
  .github/workflows/test.yml
Labels: development

#103 [FEAT] Implement pipe redirect and bind fds to stdio
  .github/workflows/test.yml
  include/defines.h
  include/executor.h
  include/utils.h
  source/backend/executor/executor.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_pipeline.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/bind.c
  source/backend/redirection/io_redirect.c
  source/backend/redirection/pipe.c
  source/backend/redirection/pipe_redirect.c
  source/backend/redirection/pipe_redirect_utils.c
  source/debug/print_cmd_table.c
  source/debug/print_expanded_cmd_table.c
  source/init_shell.c
  source/shell_clean.c
  source/utils/cmd_table_operation_utils.c
  source/utils/file_utils.c
  source/utils/final_cmd_table_utils.c
  source/utils/io_redirect_utils.c
  source/utils/process_utils.c
Labels: todo, feature

#108 [FEAT] Implement io redirection
  .github/workflows/test.yml
  Makefile
  include/builtins.h
  include/defines.h
  include/executor.h
  include/signals.h
  include/utils.h
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/singly_linked/ft_lstnew_front.c
  source/backend/executor/exec_error.c
  source/backend/executor/executor.c
  source/backend/executor/executor_utils.c
  source/backend/executor/handle_builtin.c
  source/backend/executor/handle_control_op.c
  source/backend/executor/handle_external.c
  source/backend/executor/handle_pipeline.c
  source/backend/executor/handle_simple_cmd.c
  source/backend/executor/handle_subshell.c
  source/backend/redirection/bind.c
  source/backend/redirection/heredoc.c
  source/backend/redirection/io_redirect.c
  source/backend/redirection/pipe_redirect.c
  source/builtins/echo.c
  source/builtins/exit.c
  source/debug/print_final_cmd_table.c
  source/frontend/expander/expander.c
  source/frontend/parser/cmd_table_list.c
  source/frontend/parser/parser.c
  source/frontend/parser/parser_operation.c
  source/init_shell.c
  source/main.c
  source/shell_clean.c
  source/signal/signal.c
  source/utils/cmd_table_operation_utils.c
  source/utils/cmd_table_status_utils.c
  source/utils/cmd_table_type_utils.c
  source/utils/final_cmd_table_utils.c
  source/utils/io_redirect_status_utils.c
  source/utils/process_utils.c
Labels: feature

#119 [FEAT] Implement cd builtin function
  .github/workflows/test.yml
  .vscode/launch.json
  Makefile
  include/builtins.h
  include/cd.h
  include/defines.h
  include/expander.h
  include/minishell.h
  libraries/libft/build/libft.mk
  libraries/libft/inc/libft.h
  libraries/libft/src/libft/lists/doubly_linked/ft_lstclear_d.c
  libraries/libft/src/libft/lists/doubly_linked/ft_lstdrop_node_d.c
  libraries/libft/src/libft/lists/doubly_linked/ft_lstnew_back_d.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstdrop_node.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstnew_back.c
  libraries/libft/src/libft/lists/singly_linked/ft_lstpop_front_content.c
  libraries/libft/src/libft/strings/ft_rplc_part_of_str.c
  libraries/libft/src/libft/strings/ft_strcmp.c
  libraries/libft/src/libft/strings/ft_strdel_sequence.c
  libraries/libft/src/libft/strings/ft_strncmp.c
  libraries/libft/src/libft/strings/ft_strnstr.c
  libraries/libft/src/libft/strings/ft_strrplc_sequence.c
  source/backend/executor/handle_builtin.c
  source/builtins/cd.c
  source/builtins/cd/cd.c
  source/builtins/cd/cd_errors.c
  source/builtins/cd/cd_utils.c
  source/builtins/cd/cmpnt_list.c
  source/builtins/cd/cmpnt_list_utils.c
  source/builtins/cd/dot_cmpnts.c
  source/builtins/cd/environment_utils.c
  source/builtins/cd/get_target_dir.c
  source/builtins/cd/process_path.c
  source/builtins/cd/update_pwd_env.c
  source/builtins/pwd.c
  source/frontend/expander/expand_special_param.c
  source/frontend/expander/expand_variable.c
  source/frontend/expander/parameter_expansion.c
  source/frontend/expander/quote_removal.c
  source/frontend/expander/replace_part_of_str.c
  source/init_shell.c
  source/utils/final_cmd_table_utils.c
Labels: feature

#136 [CI] Trigger GH Action for every pull request to any branch and print the commands that caused changes in the tester
  .github/workflows/test.yml
  Makefile
Labels: development

#129 [FIX] Set exit code to 2 if syntax error is found
  include/defines.h
  source/frontend/parser/parser.c
Labels: bug

#137 [SUGGESTION] Let ft_snprintf() append to the string instead of always rewriting it
  source/builtins/echo.c
Labels: enhancement

#133 [FIX] Combine echo args into one string
  source/builtins/echo.c
Labels: bug
